/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbyan' at '6/21/17 10:51 AM' with Gradle 2.13
 *
 * @author sbyan, @date 6/21/17 10:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
