import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sbyan' at '6/21/17 10:51 AM' with Gradle 2.13
 *
 * @author sbyan, @date 6/21/17 10:51 AM
 */
public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
