package cn.com.easystudio.api.customer;/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbyan' at '6/21/17 10:51 AM' with Gradle 2.13
 *
 * @author sbyan, @date 6/21/17 10:51 AM
 */


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CustomerApiApplication {
    public static void main(String[] args) {
        SpringApplication.run(CustomerApiApplication.class, args);
    }
}
